FROM node:18 as builder
WORKDIR /app
RUN apt update && \
    apt install curl git -y
RUN git clone https://github.com/youssef-of-web/internationalization.git .
RUN npm i
RUN npm run build
FROM nginx:1.21.0-alpine as production
ENV NODE_ENV production
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]



